//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:29:59 PM GMT 
//


package org.enotron.simulator.web_service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.enotron.simulator.web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListGridsimsRequest_QNAME = new QName("http://simulator.enotron.org/web-service", "listGridsimsRequest");
    private final static QName _MetadataRequest_QNAME = new QName("http://simulator.enotron.org/web-service", "metadataRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.enotron.simulator.web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MetadataResponse }
     * 
     */
    public MetadataResponse createMetadataResponse() {
        return new MetadataResponse();
    }

    /**
     * Create an instance of {@link SimulatorMetadata }
     * 
     */
    public SimulatorMetadata createSimulatorMetadata() {
        return new SimulatorMetadata();
    }

    /**
     * Create an instance of {@link StartGridsimFault }
     * 
     */
    public StartGridsimFault createStartGridsimFault() {
        return new StartGridsimFault();
    }

    /**
     * Create an instance of {@link StopGridsimResponse }
     * 
     */
    public StopGridsimResponse createStopGridsimResponse() {
        return new StopGridsimResponse();
    }

    /**
     * Create an instance of {@link SimulatorRun }
     * 
     */
    public SimulatorRun createSimulatorRun() {
        return new SimulatorRun();
    }

    /**
     * Create an instance of {@link DeleteGridsimResponse }
     * 
     */
    public DeleteGridsimResponse createDeleteGridsimResponse() {
        return new DeleteGridsimResponse();
    }

    /**
     * Create an instance of {@link SimulatorDetails }
     * 
     */
    public SimulatorDetails createSimulatorDetails() {
        return new SimulatorDetails();
    }

    /**
     * Create an instance of {@link DeleteGridsimFault }
     * 
     */
    public DeleteGridsimFault createDeleteGridsimFault() {
        return new DeleteGridsimFault();
    }

    /**
     * Create an instance of {@link CreateGridsimResponse }
     * 
     */
    public CreateGridsimResponse createCreateGridsimResponse() {
        return new CreateGridsimResponse();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link DeleteGridsimRequest }
     * 
     */
    public DeleteGridsimRequest createDeleteGridsimRequest() {
        return new DeleteGridsimRequest();
    }

    /**
     * Create an instance of {@link CallContext }
     * 
     */
    public CallContext createCallContext() {
        return new CallContext();
    }

    /**
     * Create an instance of {@link StopGridsimFault }
     * 
     */
    public StopGridsimFault createStopGridsimFault() {
        return new StopGridsimFault();
    }

    /**
     * Create an instance of {@link GetDataFault }
     * 
     */
    public GetDataFault createGetDataFault() {
        return new GetDataFault();
    }

    /**
     * Create an instance of {@link StartGridsimResponse }
     * 
     */
    public StartGridsimResponse createStartGridsimResponse() {
        return new StartGridsimResponse();
    }

    /**
     * Create an instance of {@link StopGridsimRequest }
     * 
     */
    public StopGridsimRequest createStopGridsimRequest() {
        return new StopGridsimRequest();
    }

    /**
     * Create an instance of {@link GetDataResponse }
     * 
     */
    public GetDataResponse createGetDataResponse() {
        return new GetDataResponse();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link CreateGridsimRequest }
     * 
     */
    public CreateGridsimRequest createCreateGridsimRequest() {
        return new CreateGridsimRequest();
    }

    /**
     * Create an instance of {@link CreateGridsimFault }
     * 
     */
    public CreateGridsimFault createCreateGridsimFault() {
        return new CreateGridsimFault();
    }

    /**
     * Create an instance of {@link GetDataRequest }
     * 
     */
    public GetDataRequest createGetDataRequest() {
        return new GetDataRequest();
    }

    /**
     * Create an instance of {@link ListGridsimsResponse }
     * 
     */
    public ListGridsimsResponse createListGridsimsResponse() {
        return new ListGridsimsResponse();
    }

    /**
     * Create an instance of {@link SimulatorDetailsAndRun }
     * 
     */
    public SimulatorDetailsAndRun createSimulatorDetailsAndRun() {
        return new SimulatorDetailsAndRun();
    }

    /**
     * Create an instance of {@link StartGridsimRequest }
     * 
     */
    public StartGridsimRequest createStartGridsimRequest() {
        return new StartGridsimRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://simulator.enotron.org/web-service", name = "listGridsimsRequest")
    public JAXBElement<Object> createListGridsimsRequest(Object value) {
        return new JAXBElement<Object>(_ListGridsimsRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://simulator.enotron.org/web-service", name = "metadataRequest")
    public JAXBElement<Object> createMetadataRequest(Object value) {
        return new JAXBElement<Object>(_MetadataRequest_QNAME, Object.class, null, value);
    }

}
