//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:29:59 PM GMT 
//


package org.enotron.simulator.web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simulatorDetailsAndRun complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulatorDetailsAndRun">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="simulatorDetails" type="{http://simulator.enotron.org/web-service}simulatorDetails"/>
 *         &lt;element name="simulatorRun" type="{http://simulator.enotron.org/web-service}simulatorRun"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulatorDetailsAndRun", propOrder = {
    "simulatorDetails",
    "simulatorRun"
})
public class SimulatorDetailsAndRun {

    @XmlElement(required = true)
    protected SimulatorDetails simulatorDetails;
    @XmlElement(required = true)
    protected SimulatorRun simulatorRun;

    /**
     * Gets the value of the simulatorDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SimulatorDetails }
     *     
     */
    public SimulatorDetails getSimulatorDetails() {
        return simulatorDetails;
    }

    /**
     * Sets the value of the simulatorDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulatorDetails }
     *     
     */
    public void setSimulatorDetails(SimulatorDetails value) {
        this.simulatorDetails = value;
    }

    /**
     * Gets the value of the simulatorRun property.
     * 
     * @return
     *     possible object is
     *     {@link SimulatorRun }
     *     
     */
    public SimulatorRun getSimulatorRun() {
        return simulatorRun;
    }

    /**
     * Sets the value of the simulatorRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulatorRun }
     *     
     */
    public void setSimulatorRun(SimulatorRun value) {
        this.simulatorRun = value;
    }

}
