//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:29:59 PM GMT 
//


package org.enotron.simulator.web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="simulatorUid" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *         &lt;element name="runDetails" type="{http://simulator.enotron.org/web-service}simulatorRun"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "simulatorUid",
    "runDetails"
})
@XmlRootElement(name = "stopGridsimResponse")
public class StopGridsimResponse {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] simulatorUid;
    @XmlElement(required = true)
    protected SimulatorRun runDetails;

    /**
     * Gets the value of the simulatorUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSimulatorUid() {
        return simulatorUid;
    }

    /**
     * Sets the value of the simulatorUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimulatorUid(byte[] value) {
        this.simulatorUid = value;
    }

    /**
     * Gets the value of the runDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SimulatorRun }
     *     
     */
    public SimulatorRun getRunDetails() {
        return runDetails;
    }

    /**
     * Sets the value of the runDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimulatorRun }
     *     
     */
    public void setRunDetails(SimulatorRun value) {
        this.runDetails = value;
    }

}
