//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.14 at 05:29:59 PM GMT 
//


package org.enotron.simulator.web_service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeScope.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="timeScope">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MINUTE"/>
 *     &lt;enumeration value="TENMINUTE"/>
 *     &lt;enumeration value="THIRTYMINUTE"/>
 *     &lt;enumeration value="HOUR"/>
 *     &lt;enumeration value="HALFDAY"/>
 *     &lt;enumeration value="DAY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "timeScope")
@XmlEnum
public enum TimeScope {

    MINUTE,
    TENMINUTE,
    THIRTYMINUTE,
    HOUR,
    HALFDAY,
    DAY;

    public String value() {
        return name();
    }

    public static TimeScope fromValue(String v) {
        return valueOf(v);
    }

}
